version: '3.8'

services:
  dontpiss:
    build: .
    container_name: dontpiss
    devices:
      # Allow access to webcam (adjust device number if needed)
      - /dev/video0:/dev/video0
    volumes:
      # Persist data, logs, and configs
      - ./data:/app/data
      - ./logs:/app/logs
      - ./analytics:/app/analytics
      - ./sounds:/app/sounds
      - ./zone_config.json:/app/zone_config.json:ro
      - ./src/zone_config.json:/app/src/zone_config.json:ro
    environment:
      - DISPLAY=${DISPLAY}
      - TRAINING_MODE=standard
    network_mode: host
    # Restart policy
    restart: unless-stopped
    # Optional: limit resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 2G

  # Optional: Setup zone using Docker
  zone-setup:
    build: .
    container_name: dontpiss-setup
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./zone_config.json:/app/zone_config.json
      - ./src/zone_config.json:/app/src/zone_config.json
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    command: python quick_zone_setup.py
    profiles:
      - setup
